/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IFinalLotteryInterface extends utils.Interface {
  functions: {
    "buyTicket(bytes32,int256)": FunctionFragment;
    "calculateSinglePriceValue(uint256,uint256)": FunctionFragment;
    "calculateTotalPriceValue(uint256)": FunctionFragment;
    "checkIfTicketWon(uint256,uint256)": FunctionFragment;
    "collectTicketPrize(uint256,uint256)": FunctionFragment;
    "collectTicketRefund(uint256)": FunctionFragment;
    "depositEther()": FunctionFragment;
    "findTicketInfosFromNo(uint256)": FunctionFragment;
    "getIthOwnedTicketNo(uint256,uint256)": FunctionFragment;
    "getIthWinningTicket(uint256,uint256)": FunctionFragment;
    "getLastOwnedTicketNo(uint256)": FunctionFragment;
    "getRandomNumber()": FunctionFragment;
    "getTicketInfo(uint256)": FunctionFragment;
    "getamount(uint8)": FunctionFragment;
    "lotteryNoCalculator()": FunctionFragment;
    "pickWinner(uint256)": FunctionFragment;
    "revealRndNumber(uint256,uint256)": FunctionFragment;
    "transferAmount(uint256,uint256)": FunctionFragment;
    "withdrawEther(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyTicket"
      | "calculateSinglePriceValue"
      | "calculateTotalPriceValue"
      | "checkIfTicketWon"
      | "collectTicketPrize"
      | "collectTicketRefund"
      | "depositEther"
      | "findTicketInfosFromNo"
      | "getIthOwnedTicketNo"
      | "getIthWinningTicket"
      | "getLastOwnedTicketNo"
      | "getRandomNumber"
      | "getTicketInfo"
      | "getamount"
      | "lotteryNoCalculator"
      | "pickWinner"
      | "revealRndNumber"
      | "transferAmount"
      | "withdrawEther"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateSinglePriceValue",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateTotalPriceValue",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIfTicketWon",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectTicketPrize",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectTicketRefund",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEther",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "findTicketInfosFromNo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getIthOwnedTicketNo",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getIthWinningTicket",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastOwnedTicketNo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRandomNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketInfo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getamount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryNoCalculator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pickWinner",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "revealRndNumber",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAmount",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEther",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateSinglePriceValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateTotalPriceValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkIfTicketWon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectTicketPrize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectTicketRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findTicketInfosFromNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIthOwnedTicketNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIthWinningTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastOwnedTicketNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getamount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lotteryNoCalculator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pickWinner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revealRndNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEther",
    data: BytesLike
  ): Result;

  events: {
    "AmountOfPrize(string,uint256)": EventFragment;
    "SinglePriceVal(uint256)": EventFragment;
    "Winner(bool)": EventFragment;
    "WinningTicket(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AmountOfPrize"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SinglePriceVal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Winner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WinningTicket"): EventFragment;
}

export interface AmountOfPrizeEventObject {
  prizeName: string;
  prize: BigNumber;
}
export type AmountOfPrizeEvent = TypedEvent<
  [string, BigNumber],
  AmountOfPrizeEventObject
>;

export type AmountOfPrizeEventFilter = TypedEventFilter<AmountOfPrizeEvent>;

export interface SinglePriceValEventObject {
  totalPrice: BigNumber;
}
export type SinglePriceValEvent = TypedEvent<
  [BigNumber],
  SinglePriceValEventObject
>;

export type SinglePriceValEventFilter = TypedEventFilter<SinglePriceValEvent>;

export interface WinnerEventObject {
  isWin: boolean;
}
export type WinnerEvent = TypedEvent<[boolean], WinnerEventObject>;

export type WinnerEventFilter = TypedEventFilter<WinnerEvent>;

export interface WinningTicketEventObject {
  ticketNo: BigNumber;
  amount: BigNumber;
}
export type WinningTicketEvent = TypedEvent<
  [BigNumber, BigNumber],
  WinningTicketEventObject
>;

export type WinningTicketEventFilter = TypedEventFilter<WinningTicketEvent>;

export interface IFinalLottery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFinalLotteryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyTicket(
      hash_rnd_number: PromiseOrValue<BytesLike>,
      tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    calculateSinglePriceValue(
      thPrice: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    calculateTotalPriceValue(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkIfTicketWon(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectTicketPrize(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectTicketRefund(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositEther(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    findTicketInfosFromNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getIthOwnedTicketNo(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getIthWinningTicket(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getLastOwnedTicketNo(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    getRandomNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTicketInfo(
      ticket_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getamount(
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lotteryNoCalculator(overrides?: CallOverrides): Promise<[BigNumber]>;

    pickWinner(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revealRndNumber(
      ticket_no: PromiseOrValue<BigNumberish>,
      random_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferAmount(
      lottery_no: PromiseOrValue<BigNumberish>,
      prize: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyTicket(
    hash_rnd_number: PromiseOrValue<BytesLike>,
    tier: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  calculateSinglePriceValue(
    thPrice: PromiseOrValue<BigNumberish>,
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  calculateTotalPriceValue(
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkIfTicketWon(
    lottery_no: PromiseOrValue<BigNumberish>,
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectTicketPrize(
    lottery_no: PromiseOrValue<BigNumberish>,
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectTicketRefund(
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositEther(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  findTicketInfosFromNo(
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getIthOwnedTicketNo(
    i: PromiseOrValue<BigNumberish>,
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getIthWinningTicket(
    i: PromiseOrValue<BigNumberish>,
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getLastOwnedTicketNo(
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, number]>;

  getRandomNumber(overrides?: CallOverrides): Promise<BigNumber>;

  getTicketInfo(
    ticket_number: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getamount(
    tier: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lotteryNoCalculator(overrides?: CallOverrides): Promise<BigNumber>;

  pickWinner(
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revealRndNumber(
    ticket_no: PromiseOrValue<BigNumberish>,
    random_number: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferAmount(
    lottery_no: PromiseOrValue<BigNumberish>,
    prize: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawEther(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyTicket(
      hash_rnd_number: PromiseOrValue<BytesLike>,
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    calculateSinglePriceValue(
      thPrice: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculateTotalPriceValue(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkIfTicketWon(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectTicketPrize(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectTicketRefund(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositEther(overrides?: CallOverrides): Promise<void>;

    findTicketInfosFromNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getIthOwnedTicketNo(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    getIthWinningTicket(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { ticket_no: BigNumber; amount: BigNumber }
    >;

    getLastOwnedTicketNo(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    getRandomNumber(overrides?: CallOverrides): Promise<BigNumber>;

    getTicketInfo(
      ticket_number: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getamount(
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lotteryNoCalculator(overrides?: CallOverrides): Promise<BigNumber>;

    pickWinner(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    revealRndNumber(
      ticket_no: PromiseOrValue<BigNumberish>,
      random_number: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferAmount(
      lottery_no: PromiseOrValue<BigNumberish>,
      prize: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AmountOfPrize(string,uint256)"(
      prizeName?: null,
      prize?: null
    ): AmountOfPrizeEventFilter;
    AmountOfPrize(prizeName?: null, prize?: null): AmountOfPrizeEventFilter;

    "SinglePriceVal(uint256)"(totalPrice?: null): SinglePriceValEventFilter;
    SinglePriceVal(totalPrice?: null): SinglePriceValEventFilter;

    "Winner(bool)"(isWin?: null): WinnerEventFilter;
    Winner(isWin?: null): WinnerEventFilter;

    "WinningTicket(uint256,uint256)"(
      ticketNo?: null,
      amount?: null
    ): WinningTicketEventFilter;
    WinningTicket(ticketNo?: null, amount?: null): WinningTicketEventFilter;
  };

  estimateGas: {
    buyTicket(
      hash_rnd_number: PromiseOrValue<BytesLike>,
      tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    calculateSinglePriceValue(
      thPrice: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    calculateTotalPriceValue(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkIfTicketWon(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectTicketPrize(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectTicketRefund(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositEther(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    findTicketInfosFromNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getIthOwnedTicketNo(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getIthWinningTicket(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getLastOwnedTicketNo(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRandomNumber(overrides?: CallOverrides): Promise<BigNumber>;

    getTicketInfo(
      ticket_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getamount(
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lotteryNoCalculator(overrides?: CallOverrides): Promise<BigNumber>;

    pickWinner(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revealRndNumber(
      ticket_no: PromiseOrValue<BigNumberish>,
      random_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferAmount(
      lottery_no: PromiseOrValue<BigNumberish>,
      prize: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTicket(
      hash_rnd_number: PromiseOrValue<BytesLike>,
      tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    calculateSinglePriceValue(
      thPrice: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    calculateTotalPriceValue(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkIfTicketWon(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectTicketPrize(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectTicketRefund(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositEther(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    findTicketInfosFromNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getIthOwnedTicketNo(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getIthWinningTicket(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getLastOwnedTicketNo(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRandomNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTicketInfo(
      ticket_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getamount(
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lotteryNoCalculator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pickWinner(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revealRndNumber(
      ticket_no: PromiseOrValue<BigNumberish>,
      random_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferAmount(
      lottery_no: PromiseOrValue<BigNumberish>,
      prize: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
