/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface FinalLotteryInterface extends utils.Interface {
  functions: {
    "balance(address)": FunctionFragment;
    "buyTicket(bytes32,int256)": FunctionFragment;
    "checkIfTicketWon(uint256,uint256)": FunctionFragment;
    "collectTicketPrize(uint256,uint256)": FunctionFragment;
    "collectTicketRefund(uint256)": FunctionFragment;
    "depositEther()": FunctionFragment;
    "findLotteryNoFromTicketNo(uint256)": FunctionFragment;
    "findTicketInfosFromNo(uint256)": FunctionFragment;
    "getBalance()": FunctionFragment;
    "getIthOwnedTicketNo(uint256,uint256)": FunctionFragment;
    "getIthWinningTicket(uint256,uint256)": FunctionFragment;
    "getLastOwnedTicketNo(uint256)": FunctionFragment;
    "getamount(uint8)": FunctionFragment;
    "hashOfANum(uint256)": FunctionFragment;
    "lotteryInfos(uint256)": FunctionFragment;
    "lotteryNoCalculator()": FunctionFragment;
    "moneyCollectedForEachLottery(uint256)": FunctionFragment;
    "revealRndNumber(uint256,uint256)": FunctionFragment;
    "ticketNosArray(address,uint256)": FunctionFragment;
    "totalPrizeMoney(uint256)": FunctionFragment;
    "withdrawEther(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "balance"
      | "buyTicket"
      | "checkIfTicketWon"
      | "collectTicketPrize"
      | "collectTicketRefund"
      | "depositEther"
      | "findLotteryNoFromTicketNo"
      | "findTicketInfosFromNo"
      | "getBalance"
      | "getIthOwnedTicketNo"
      | "getIthWinningTicket"
      | "getLastOwnedTicketNo"
      | "getamount"
      | "hashOfANum"
      | "lotteryInfos"
      | "lotteryNoCalculator"
      | "moneyCollectedForEachLottery"
      | "revealRndNumber"
      | "ticketNosArray"
      | "totalPrizeMoney"
      | "withdrawEther"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balance",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIfTicketWon",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectTicketPrize",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "collectTicketRefund",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEther",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "findLotteryNoFromTicketNo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "findTicketInfosFromNo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getIthOwnedTicketNo",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getIthWinningTicket",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastOwnedTicketNo",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getamount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "hashOfANum",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryInfos",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryNoCalculator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "moneyCollectedForEachLottery",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "revealRndNumber",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketNosArray",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPrizeMoney",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawEther",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "balance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkIfTicketWon",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectTicketPrize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectTicketRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findLotteryNoFromTicketNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "findTicketInfosFromNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIthOwnedTicketNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIthWinningTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastOwnedTicketNo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getamount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashOfANum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lotteryInfos",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lotteryNoCalculator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moneyCollectedForEachLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealRndNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketNosArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPrizeMoney",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawEther",
    data: BytesLike
  ): Result;

  events: {
    "AmountOfPrize(string,uint256)": EventFragment;
    "SinglePriceVal(uint256)": EventFragment;
    "TicketInfo(uint256,uint256,bytes32,uint8,bool,uint8)": EventFragment;
    "Winner(bool)": EventFragment;
    "WinningTicket(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AmountOfPrize"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SinglePriceVal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Winner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WinningTicket"): EventFragment;
}

export interface AmountOfPrizeEventObject {
  prizeName: string;
  prize: BigNumber;
}
export type AmountOfPrizeEvent = TypedEvent<
  [string, BigNumber],
  AmountOfPrizeEventObject
>;

export type AmountOfPrizeEventFilter = TypedEventFilter<AmountOfPrizeEvent>;

export interface SinglePriceValEventObject {
  totalPrice: BigNumber;
}
export type SinglePriceValEvent = TypedEvent<
  [BigNumber],
  SinglePriceValEventObject
>;

export type SinglePriceValEventFilter = TypedEventFilter<SinglePriceValEvent>;

export interface TicketInfoEventObject {
  ticketNo: BigNumber;
  lotteryNo: BigNumber;
  ticketHash: string;
  status: number;
  active: boolean;
  ticketTier: number;
}
export type TicketInfoEvent = TypedEvent<
  [BigNumber, BigNumber, string, number, boolean, number],
  TicketInfoEventObject
>;

export type TicketInfoEventFilter = TypedEventFilter<TicketInfoEvent>;

export interface WinnerEventObject {
  isWin: boolean;
}
export type WinnerEvent = TypedEvent<[boolean], WinnerEventObject>;

export type WinnerEventFilter = TypedEventFilter<WinnerEvent>;

export interface WinningTicketEventObject {
  ticketNo: BigNumber;
  amount: BigNumber;
}
export type WinningTicketEvent = TypedEvent<
  [BigNumber, BigNumber],
  WinningTicketEventObject
>;

export type WinningTicketEventFilter = TypedEventFilter<WinningTicketEvent>;

export interface FinalLottery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FinalLotteryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    balance(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    buyTicket(
      hash_rnd_number: PromiseOrValue<BytesLike>,
      tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkIfTicketWon(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectTicketPrize(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    collectTicketRefund(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositEther(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    findLotteryNoFromTicketNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    findTicketInfosFromNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    getIthOwnedTicketNo(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    getIthWinningTicket(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getLastOwnedTicketNo(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    getamount(
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    hashOfANum(
      num: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    lotteryInfos(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        lotteryNo: BigNumber;
        startTimestamp: BigNumber;
      }
    >;

    lotteryNoCalculator(overrides?: CallOverrides): Promise<[BigNumber]>;

    moneyCollectedForEachLottery(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    revealRndNumber(
      ticket_no: PromiseOrValue<BigNumberish>,
      random_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    ticketNosArray(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalPrizeMoney(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdrawEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  balance(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  buyTicket(
    hash_rnd_number: PromiseOrValue<BytesLike>,
    tier: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkIfTicketWon(
    lottery_no: PromiseOrValue<BigNumberish>,
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectTicketPrize(
    lottery_no: PromiseOrValue<BigNumberish>,
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  collectTicketRefund(
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositEther(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  findLotteryNoFromTicketNo(
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  findTicketInfosFromNo(
    ticket_no: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  getBalance(overrides?: CallOverrides): Promise<BigNumber>;

  getIthOwnedTicketNo(
    i: PromiseOrValue<BigNumberish>,
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, number]>;

  getIthWinningTicket(
    i: PromiseOrValue<BigNumberish>,
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getLastOwnedTicketNo(
    lottery_no: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, number]>;

  getamount(
    tier: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  hashOfANum(
    num: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  lotteryInfos(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { lotteryNo: BigNumber; startTimestamp: BigNumber }
  >;

  lotteryNoCalculator(overrides?: CallOverrides): Promise<BigNumber>;

  moneyCollectedForEachLottery(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  revealRndNumber(
    ticket_no: PromiseOrValue<BigNumberish>,
    random_number: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  ticketNosArray(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalPrizeMoney(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawEther(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    balance(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyTicket(
      hash_rnd_number: PromiseOrValue<BytesLike>,
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkIfTicketWon(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectTicketPrize(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    collectTicketRefund(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositEther(overrides?: CallOverrides): Promise<void>;

    findLotteryNoFromTicketNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    findTicketInfosFromNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    getBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getIthOwnedTicketNo(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    getIthWinningTicket(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { ticket_no: BigNumber; amount: BigNumber }
    >;

    getLastOwnedTicketNo(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, number]>;

    getamount(
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashOfANum(
      num: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    lotteryInfos(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        lotteryNo: BigNumber;
        startTimestamp: BigNumber;
      }
    >;

    lotteryNoCalculator(overrides?: CallOverrides): Promise<BigNumber>;

    moneyCollectedForEachLottery(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revealRndNumber(
      ticket_no: PromiseOrValue<BigNumberish>,
      random_number: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    ticketNosArray(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalPrizeMoney(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AmountOfPrize(string,uint256)"(
      prizeName?: null,
      prize?: null
    ): AmountOfPrizeEventFilter;
    AmountOfPrize(prizeName?: null, prize?: null): AmountOfPrizeEventFilter;

    "SinglePriceVal(uint256)"(totalPrice?: null): SinglePriceValEventFilter;
    SinglePriceVal(totalPrice?: null): SinglePriceValEventFilter;

    "TicketInfo(uint256,uint256,bytes32,uint8,bool,uint8)"(
      ticketNo?: null,
      lotteryNo?: null,
      ticketHash?: null,
      status?: null,
      active?: null,
      ticketTier?: null
    ): TicketInfoEventFilter;
    TicketInfo(
      ticketNo?: null,
      lotteryNo?: null,
      ticketHash?: null,
      status?: null,
      active?: null,
      ticketTier?: null
    ): TicketInfoEventFilter;

    "Winner(bool)"(isWin?: null): WinnerEventFilter;
    Winner(isWin?: null): WinnerEventFilter;

    "WinningTicket(uint256,uint256)"(
      ticketNo?: null,
      amount?: null
    ): WinningTicketEventFilter;
    WinningTicket(ticketNo?: null, amount?: null): WinningTicketEventFilter;
  };

  estimateGas: {
    balance(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyTicket(
      hash_rnd_number: PromiseOrValue<BytesLike>,
      tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkIfTicketWon(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectTicketPrize(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    collectTicketRefund(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositEther(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    findLotteryNoFromTicketNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    findTicketInfosFromNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getIthOwnedTicketNo(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIthWinningTicket(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getLastOwnedTicketNo(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getamount(
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashOfANum(
      num: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lotteryInfos(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lotteryNoCalculator(overrides?: CallOverrides): Promise<BigNumber>;

    moneyCollectedForEachLottery(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revealRndNumber(
      ticket_no: PromiseOrValue<BigNumberish>,
      random_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    ticketNosArray(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalPrizeMoney(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balance(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyTicket(
      hash_rnd_number: PromiseOrValue<BytesLike>,
      tier: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkIfTicketWon(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectTicketPrize(
      lottery_no: PromiseOrValue<BigNumberish>,
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    collectTicketRefund(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositEther(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    findLotteryNoFromTicketNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    findTicketInfosFromNo(
      ticket_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getIthOwnedTicketNo(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIthWinningTicket(
      i: PromiseOrValue<BigNumberish>,
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getLastOwnedTicketNo(
      lottery_no: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getamount(
      tier: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashOfANum(
      num: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lotteryInfos(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lotteryNoCalculator(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    moneyCollectedForEachLottery(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revealRndNumber(
      ticket_no: PromiseOrValue<BigNumberish>,
      random_number: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    ticketNosArray(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalPrizeMoney(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawEther(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
