/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lotteryv2Sol from "./Lotteryv2.sol";
export type { lotteryv2Sol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { DALottery } from "./Lotteryv2.sol/DALottery";
export { DALottery__factory } from "./factories/Lotteryv2.sol/DALottery__factory";
